name: build_and_release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install nuitka
          pip install -r requirements.txt

      - name: Build
        run: >
          nuitka --standalone --onefile
          --enable-plugin=tk-inter
          --windows-disable-console
          --windows-icon-from-ico=logo.ico
          --lto=yes
          --output-dir=dist
          main.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/main.exe
          generate_release_notes: true
